#!/usr/bin/env python3
"""
HTML Report Generator

Generates interactive HTML reports with Plotly charts.
"""

from typing import Optional, Dict, Any
import json

from config import Config


class HTMLReportGenerator:
    """
    Generates interactive HTML reports.
    """
    
    def __init__(self, config: Optional[Config] = None):
        self.config = config or Config()
    
    def generate(
        self,
        summary=None,
        tcp_analysis=None,
        dns_analysis=None,
        latency_analysis=None,
        findings=None,
    ) -> str:
        """Generate full HTML report."""
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PCAP Analysis Report</title>
    <script src="https://cdn.plot.ly/plotly-2.24.1.min.js"></script>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; line-height: 1.6; }}
        .container {{ max-width: 1400px; margin: 0 auto; padding: 20px; }}
        header {{ background: linear-gradient(135deg, #1a237e 0%, #0d47a1 100%); color: white; padding: 30px; margin-bottom: 20px; border-radius: 8px; }}
        h1 {{ font-size: 2em; margin-bottom: 10px; }}
        h2 {{ color: #1a237e; margin: 20px 0 15px; padding-bottom: 10px; border-bottom: 2px solid #e0e0e0; }}
        h3 {{ color: #333; margin: 15px 0 10px; }}
        .card {{ background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .stats-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 15px 0; }}
        .stat-card {{ background: #f8f9fa; padding: 15px; border-radius: 6px; text-align: center; }}
        .stat-value {{ font-size: 2em; font-weight: bold; color: #1a237e; }}
        .stat-label {{ color: #666; font-size: 0.9em; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #e0e0e0; }}
        th {{ background: #f5f5f5; font-weight: 600; }}
        tr:hover {{ background: #f8f9fa; }}
        .severity-critical {{ background: #b71c1c; color: white; }}
        .severity-high {{ background: #d32f2f; color: white; }}
        .severity-medium {{ background: #f57c00; color: white; }}
        .severity-low {{ background: #1976d2; color: white; }}
        .severity-info {{ background: #388e3c; color: white; }}
        .finding {{ border-left: 4px solid; padding: 15px; margin: 15px 0; background: #fafafa; border-radius: 0 6px 6px 0; }}
        .finding.critical {{ border-color: #b71c1c; }}
        .finding.high {{ border-color: #d32f2f; }}
        .finding.medium {{ border-color: #f57c00; }}
        .finding.low {{ border-color: #1976d2; }}
        .badge {{ display: inline-block; padding: 3px 8px; border-radius: 4px; font-size: 0.8em; font-weight: bold; }}
        .chart-container {{ height: 400px; margin: 20px 0; }}
        .recommendations {{ background: #e3f2fd; padding: 15px; border-radius: 6px; margin-top: 10px; }}
        .recommendations li {{ margin: 5px 0; }}
        footer {{ text-align: center; padding: 20px; color: #666; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>📊 PCAP Analysis Report</h1>
            <p>Generated by Advanced PCAP Analyzer</p>
        </header>
        
        {self._generate_summary_section(summary)}
        {self._generate_findings_section(findings)}
        {self._generate_tcp_section(tcp_analysis)}
        {self._generate_dns_section(dns_analysis)}
        {self._generate_latency_section(latency_analysis)}
        
        <footer>
            <p>Report generated by Advanced PCAP Analyzer v1.0.0</p>
        </footer>
    </div>
    
    <script>
        // Initialize Plotly charts
        document.addEventListener('DOMContentLoaded', function() {{
            {self._generate_charts(summary, tcp_analysis, dns_analysis, latency_analysis)}
        }});
    </script>
</body>
</html>"""
        
        return html
    
    def _generate_summary_section(self, summary) -> str:
        """Generate summary section HTML."""
        if not summary:
            return ""
        
        return f"""
        <section class="card">
            <h2>📋 Capture Summary</h2>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-value">{summary.total_packets:,}</div>
                    <div class="stat-label">Total Packets</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{summary.duration_seconds:.1f}s</div>
                    <div class="stat-label">Duration</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{summary.total_bytes:,}</div>
                    <div class="stat-label">Total Bytes</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{summary.retransmission_count:,}</div>
                    <div class="stat-label">Retransmissions</div>
                </div>
            </div>
            
            <h3>Protocol Distribution</h3>
            <table>
                <tr><th>Protocol</th><th>Packets</th><th>Percentage</th></tr>
                {"".join(f'<tr><td>{proto}</td><td>{count:,}</td><td>{(count/max(1,sum(summary.protocol_counts.values())))*100:.1f}%</td></tr>' for proto, count in summary.protocol_counts.items())}
            </table>
        </section>
        """
    
    def _generate_findings_section(self, findings) -> str:
        """Generate findings section HTML."""
        if not findings:
            return '<section class="card"><h2>✅ Findings</h2><p>No significant issues detected.</p></section>'
        
        findings_html = ""
        for f in findings:
            findings_html += f"""
            <div class="finding {f.severity.value}">
                <span class="badge severity-{f.severity.value}">{f.severity.value.upper()}</span>
                <strong>{f.finding_id}</strong>: {f.title}
                <p>{f.description}</p>
                <p><strong>Affected:</strong> {f.affected_object or 'N/A'}</p>
                <div class="recommendations">
                    <strong>Recommended Actions:</strong>
                    <ul>
                        {"".join(f"<li>{a}</li>" for a in f.recommended_actions[:3])}
                    </ul>
                </div>
            </div>
            """
        
        return f"""
        <section class="card">
            <h2>⚠️ Findings ({len(findings)})</h2>
            {findings_html}
        </section>
        """
    
    def _generate_tcp_section(self, tcp_analysis) -> str:
        """Generate TCP analysis section HTML."""
        if not tcp_analysis:
            return ""
        
        return f"""
        <section class="card">
            <h2>🔌 TCP Health Analysis</h2>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-value">{tcp_analysis.total_connections}</div>
                    <div class="stat-label">Connections</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{tcp_analysis.successful_connections}</div>
                    <div class="stat-label">Successful</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{tcp_analysis.failed_connection_count}</div>
                    <div class="stat-label">Failed</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{tcp_analysis.overall_retransmission_rate:.2f}%</div>
                    <div class="stat-label">Retrans Rate</div>
                </div>
            </div>
        </section>
        """
    
    def _generate_dns_section(self, dns_analysis) -> str:
        """Generate DNS analysis section HTML."""
        if not dns_analysis:
            return ""
        
        return f"""
        <section class="card">
            <h2>🌐 DNS Analysis</h2>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-value">{dns_analysis.total_queries}</div>
                    <div class="stat-label">Queries</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{dns_analysis.avg_latency_ms:.1f}ms</div>
                    <div class="stat-label">Avg Latency</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{dns_analysis.nxdomain_count}</div>
                    <div class="stat-label">NXDOMAIN</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{dns_analysis.slow_queries_count}</div>
                    <div class="stat-label">Slow Queries</div>
                </div>
            </div>
        </section>
        """
    
    def _generate_latency_section(self, latency_analysis) -> str:
        """Generate latency analysis section HTML."""
        if not latency_analysis:
            return ""
        
        return f"""
        <section class="card">
            <h2>⏱️ Latency Analysis</h2>
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-value">{latency_analysis.avg_tcp_rtt_ms:.1f}ms</div>
                    <div class="stat-label">TCP Avg RTT</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{latency_analysis.avg_dns_latency_ms:.1f}ms</div>
                    <div class="stat-label">DNS Avg</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">{latency_analysis.high_latency_count}</div>
                    <div class="stat-label">High Latency Events</div>
                </div>
            </div>
        </section>
        """
    
    def _generate_charts(self, summary, tcp_analysis, dns_analysis, latency_analysis) -> str:
        """Generate JavaScript for Plotly charts."""
        charts = []
        
        if summary and summary.protocol_counts:
            labels = list(summary.protocol_counts.keys())
            values = list(summary.protocol_counts.values())
            charts.append(f"""
            Plotly.newPlot('protocol-chart', 
                [{{type: 'pie', labels: {json.dumps(labels)}, values: {json.dumps(values)}}}],
                {{title: 'Protocol Distribution'}}
            );
            """)
        
        return "\n".join(charts)
